### ISSUE TITLE
Not every enum is generated

### ISSUE THREAD

**Issue by srgskiri** [mulesoft-labs/raml-dotnet-tools#178]
Hi,

I'm importing a relatively big RAML with about 15 different enums throughout the file. Upon importing, RAML tool only generates a few enums. I'm missing several enums in the generated code.

In raml, I see no difference between the generated and non-generated enums.

Any ideas?

Thanks in advance

EDIT: I notice now that the missing enums are defined in RAML in the section where i define my query parameters. The enums the are defined within schemas/types are generated as expected.

**Comment by LoulG** [comment]
Looks like it's due to a typo in the main T4, lines 1077 and 1081.
`apiEnumValues` should be `apiEnum.Values`

**Comment by woodp** [comment]
@LoulG that is already fixed on develop branch, fix will be included in next release

 @srgskiri could you please provide a simple RAML sample to reproduce the issue ?

**Comment by srgskiri** [comment]
This will reproduce the issue. Enum "GasProfile" is not generated while "VatType" is.

#%RAML 1.0
title: API
description: REST services
version: 1.2.0
protocols:
- HTTPS
baseUri: /
mediaType:
- application/json
types:
  RSupplyTariff:
    type: object
    properties:
      id:
        type: string
        required: false
      vatType:
        type: string
        enum:
        - None
        - Low
        - High
        - Unknown
        required: false
securitySchemes:
  HTTP_BASIC:
    type: Basic Authentication
    description: Basic
/api/product/{productid}/supplytariffs:
  uriParameters:
    productid:
      type: string
  get:
    displayName: Get supply tariffs
    queryParameters:
      gasRegion:
        type: integer
        description: Required for gas products
        required: false
      gasProfile:
        type: string
        enum:
        - G1
        - G2
        required: false
    responses:
      200:
        body:
          type: array
          items:
            type: RSupplyTariff

**Comment by srgskiri** [comment]
Where can I find this main T4? Or do I have to reïnstall a new .vsix with new T4?

**Comment by srgskiri** [comment]
@woodp thank you for your responses.

I'm scaffolding an asp.net WebApi so I'm using ApiEnum.t4. But unfortunatly this fixed template doesn't fix this issue I have. Are you able to reproduce it?

**Comment by majkimester** [comment]
Hello Pedro, Thank you for the fix, and now the
example from my comment https://github.com/mulesoft-labs/raml-dotnet-tools/issues/178#issuecomment-377370799 is working.

Unfortunately the an enum defined in a library is not working:

lib_enumexample.raml:
```
#%RAML 1.0 Library

types:
  MyEnum:
    type: string
    enum: [ MyValue1, MyValue2, MyValue3 ]

  ResponseType:
    type: object
    properties:
      myenum: MyEnum
      myotherenum:
        enum: [ MyValue1, MyValue2, MyValue3 ]
      myint: integer
      mystring: string
```
enum_lib.raml:
```
#%RAML 1.0
title: Example Service
version: v1.0
protocols: [ HTTP, HTTPS ]
mediaType: application/json

baseUri: http://192.168.1.1:8080/example/rest/

uses:
  libEnumExample: lib/lib_enumexample.raml

types:
  MyEnum: libEnumExample.MyEnum
  ResponseType: libEnumExample.ResponseType

/enumExample/{enumUriParam}:
  uriParameters:
    enumUriParam:
      type: MyEnum
  get:
    queryParameters:
      enumQueryParam:
        type: MyEnum
    responses:
      200:
        body:
          application/json:
            type: ResponseType
```
Result:

The MyEnum enum is generated, but never referenced:

```
	public enum LibEnumExampleMyEnum
	{
		[JsonProperty("MyValue1")]
		MyValue1,
		[JsonProperty("MyValue2")]
		MyValue2,
		[JsonProperty("MyValue3")]
		MyValue3
    }
```

It is completely missing form the ResponseType:

```
    public partial class  LibEnumExampleResponseType 
    {

		[JsonProperty("myotherenum")]
		[JsonConverter(typeof(StringEnumConverter))]
        public Myotherenum Myotherenum { get; set; }


		[JsonProperty("myint")]
        public int Myint { get; set; }


		[JsonProperty("mystring")]
        public string Mystring { get; set; }


    } // end class
```

It is generated into Query param and uri param, but only as string:

```
    public partial class  GetEnumExampleEnumUriParamQuery 
    {

		[JsonProperty("enumQueryParam")]
        public string EnumQueryParam { get; set; }


    } // end class

    /// <summary>
    /// Uri Parameters for resource /enumExample/{enumUriParam}
    /// </summary>
    public partial class  EnumExampleEnumUriParamUriParameters 
    {

		[JsonProperty("enumUriParam")]
        public string EnumUriParam { get; set; }


    } // end class
```

**Comment by jawn** [comment]
@woodp Any update?

**Comment by woodp** [comment]
@jawn 
This is fixed in the new tool. You can check the beta release: [AMF .Net Tools](https://github.com/mulesoft/amf-dotnet-tools/releases).
If you have any issues please report them in that repo.

**Comment by jawn** [comment]
Thanks, on a side note, is that tool 100% backwards compatible with this project?

**Comment by woodp** [comment]
Cannot guarantee 100% backwards compatibility. Generated code could vary from one tool to the other. It should be definitively be adopted for new projects. On the case of an existing project you should check how it will affect your code.
